### ISSUE TITLE
mailto link does not work

### ISSUE THREAD

**Issue by vjayer** [jscher2000/Yahoo-Mail-mailto-and-Email-Link-Fix#1]
Firefox 79, 64-bit, Linux and Windows
See the bottom of this page: https://platform.sh/contact/
for the link "Report a Security Issue" which is mailto:security@platform.sh?subject=Security Issue

Right clicking > New Yahoo Mail message results in a blank email, with no recipient or subject

**Comment by jscher2000** [comment]
Thank you for flagging this problem. Somehow it never occurred to me to test a mailto: link with a ? in it. I'll post an update soon.

**Comment by jscher2000** [comment]
Hopefully the updated version has been working for you.

**Comment by vjayer** [comment]
Sorry for the late reply. Yes, it's working for me, thanks for quickly fixing it!
